#!/usr/bin/env ruby

require 'rubygems'
require 'resque'
require 'resque/status'
require 'irb'

require 'basic_job'
require 'progress_job'

puts "*** Resque Jobs ***"
puts "There are currently #{Resque.workers.size} workers running"
puts
puts "Try something:"
puts
puts '---- BASIC JOB '.ljust(80, '-')
puts "Resque.enqueue(BasicJob, :id => 1)"
puts "Resque.peek :default"
puts
puts '---- JOB WITH PROGRESS '.ljust(80, '-')
puts "job_id = ProgressJob.create(:id => 2)"
puts "Resque::Status.get(job_id).inspect"
puts ''.ljust(80, '-')
puts

IRB.start
